changed test_args to TEST_ARGS
because of Python3 windows build failure
https://ci.appveyor.com/project/niccokunzmann/knittingpattern/build/1.0.3/job/2k2uw4cogddcqaeg


Build started
git clone -q --branch=master https://github.com/AllYarnsAreBeautiful/knittingpattern.git C:\projects\knittingpattern
git checkout -qf ac6becf4cd584ea469394a6c71145d5a04ee8a7e
Running Install scripts
%PYTHON%\python.exe -m pip install wheel
Requirement already satisfied (use --upgrade to upgrade): wheel in c:\python33\lib\site-packages
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
%PYTHON%\python.exe setup.py test
running test
Traceback (most recent call last):
  File "setup.py", line 300, in <module>
    main()
  File "setup.py", line 291, in main
    setuptools.setup(**METADATA)
  File "C:\Python33\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python33\lib\distutils\dist.py", line 930, in run_commands
    self.run_command(cmd)
  File "C:\Python33\lib\distutils\dist.py", line 948, in run_command
    cmd_obj.ensure_finalized()
  File "C:\Python33\lib\distutils\cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 65, in finalize_options
    self.test_args = self.TEST_ARGS
AttributeError: can't set attribute
Command exited with code 1